In [1]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
# Sample documents
documents = [
    "This is a list which containig sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings."
]

In [3]:
query = "keyword-based search"

In [4]:
import re

def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)
    return text

In [5]:
preprocess_documents = [preprocess_text(doc) for doc in documents]

In [6]:
preprocess_documents

['this is a list which containig sample documents',
 'keywords are important for keywordbased search',
 'document analysis involves extracting keywords',
 'keywordbased search relies on sparse embeddings']

In [7]:
print("Preprocessed Documents:")
for doc in preprocess_documents:
    print(doc)

Preprocessed Documents:
this is a list which containig sample documents
keywords are important for keywordbased search
document analysis involves extracting keywords
keywordbased search relies on sparse embeddings


In [8]:
preprocessed_query = preprocess_text(query)

In [9]:
preprocessed_query

'keywordbased search'

In [10]:
vector = TfidfVectorizer()

In [11]:
X = vector.fit_transform(preprocess_documents)

In [12]:
X.toarray()

array([[0.        , 0.        , 0.37796447, 0.        , 0.37796447,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
        0.        , 0.37796447, 0.        , 0.        , 0.37796447,
        0.37796447],
       [0.        , 0.4533864 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4533864 , 0.4533864 , 0.        ,
        0.        , 0.35745504, 0.35745504, 0.        , 0.        ,
        0.        , 0.        , 0.35745504, 0.        , 0.        ,
        0.        ],
       [0.46516193, 0.        , 0.        , 0.46516193, 0.        ,
        0.        , 0.46516193, 0.        , 0.        , 0.46516193,
        0.        , 0.        , 0.36673901, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.43671931, 0.        , 0.        , 0.       

In [13]:
X.toarray()[0]

array([0.        , 0.        , 0.37796447, 0.        , 0.37796447,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
       0.        , 0.37796447, 0.        , 0.        , 0.37796447,
       0.37796447])

In [14]:
X.toarray()[0].shape

(21,)

In [15]:
query_embedding = vector.transform([preprocessed_query])

In [16]:
query_embedding.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        ]])

In [17]:
similarities = cosine_similarity(X, query_embedding)

In [18]:
similarities

array([[0.        ],
       [0.50551777],
       [0.        ],
       [0.48693426]])

In [19]:
np.argsort(similarities, axis=0)

array([[0],
       [2],
       [3],
       [1]])

In [20]:
# ranking
ranked_indices = np.argsort(similarities, axis=0)[::-1].flatten()
ranked_indices

array([1, 3, 2, 0])

In [21]:
ranked_documents = [documents[i] for i in ranked_indices]
ranked_documents

['Keywords are important for keyword-based search.',
 'Keyword-based search relies on sparse embeddings.',
 'Document analysis involves extracting keywords.',
 'This is a list which containig sample documents.']

In [22]:
# output the ranked documents
for i, doc in enumerate(ranked_documents):
    print(f"Rank {i+1}: {doc}")

Rank 1: Keywords are important for keyword-based search.
Rank 2: Keyword-based search relies on sparse embeddings.
Rank 3: Document analysis involves extracting keywords.
Rank 4: This is a list which containig sample documents.


In [23]:
query

'keyword-based search'

#### **Vector Search**

In [24]:
documents = [
    "This is a list which containig sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings."
]

In [ ]:
#https://huggingface.co/sentence-transformers

In [25]:
document_embeddings = np.array([
    [0.634, 0.234, 0.867, 0.042, 0.249],
    [0.123, 0.456, 0.789, 0.321, 0.654],
    [0.987, 0.654, 0.321, 0.123, 0.456]
])

In [26]:
# Sample search query (represented as a dense vector)
query_embedding = np.array([[0.789, 0.321, 0.654, 0.987, 0.123]])

In [27]:
# Calculate cosine similarity between query and documents
similarities = cosine_similarity(document_embeddings, query_embedding)

In [28]:
similarities

array([[0.73558979],
       [0.67357898],
       [0.71517305]])

In [29]:
ranked_indices = np.argsort(similarities, axis=0)[::-1].flatten()
ranked_indices

array([0, 2, 1])

In [30]:
# Output the ranked documents
for i, idx in enumerate(ranked_indices):
    print(f"Rank {i+1}: Document {idx+1}")

Rank 1: Document 1
Rank 2: Document 3
Rank 3: Document 2


#### **RAG Retrieval**

In [31]:
doc_path = "../Retrieval-Augmented-Generation.pdf"

In [32]:
from langchain_community.document_loaders import PyPDFLoader

In [33]:
loader = PyPDFLoader(doc_path)

In [34]:
docs = loader.load()

In [35]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

In [36]:
splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)

In [37]:
chunks = splitter.split_documents(docs)
len(chunks)

158

In [38]:
import os
from dotenv import load_dotenv

load_dotenv()

os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
os.environ["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY")

In [39]:
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

In [11]:
# %pip install chromadb

In [40]:
from langchain.vectorstores import Chroma

In [41]:
vectorstore = Chroma.from_documents(chunks, embeddings)

In [42]:
vectorstore_retreiver = vectorstore.as_retriever(search_kwargs={"k": 3})

In [43]:
vectorstore_retreiver

VectorStoreRetriever(tags=['Chroma', 'OpenAIEmbeddings'], vectorstore=<langchain_community.vectorstores.chroma.Chroma object at 0x000001EC58891B20>, search_kwargs={'k': 3})

In [14]:
# %pip install rank_bm25

In [44]:
from langchain.retrievers import BM25Retriever, EnsembleRetriever

In [45]:
keyword_retriever = BM25Retriever.from_documents(chunks)
keyword_retriever

BM25Retriever(vectorizer=<rank_bm25.BM25Okapi object at 0x000001EC59CBD460>)

In [20]:
# help(keyword_retriever)

In [46]:
keyword_retriever.k

4

In [47]:
keyword_retriever.k =  3

In [48]:
ensemble_retriever = EnsembleRetriever(
    retrievers=[vectorstore_retreiver, keyword_retriever], weights=[0.3, 0.7]
)

ensemble_retriever

EnsembleRetriever(retrievers=[VectorStoreRetriever(tags=['Chroma', 'OpenAIEmbeddings'], vectorstore=<langchain_community.vectorstores.chroma.Chroma object at 0x000001EC58891B20>, search_kwargs={'k': 3}), BM25Retriever(vectorizer=<rank_bm25.BM25Okapi object at 0x000001EC59CBD460>, k=3)], weights=[0.3, 0.7])

### **Combined Vector Search and Keyword Search (Hybrid Search)**

##### **hybrid_score = (1 — alpha) * sparse_score + alpha * dense_score**

In [49]:
# from langchain_groq import ChatGroq

# llm = ChatGroq(
#     model = 'deepseek-r1-distill-llama-70b',
#     temperature=0.1
# )

In [50]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model='gpt-4o-mini',
    temperature=0.0
)

In [51]:
llm.invoke('hey, how are you ?')

AIMessage(content="I'm just a program, but I'm here and ready to help you! How can I assist you today?", additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 21, 'prompt_tokens': 13, 'total_tokens': 34, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_8bda4d3a2c', 'id': 'chatcmpl-CDpDssHgsV7Yv9vPuybLXhk8VzkOX', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='run--e363e268-fafc-4559-8547-7fdb2de0bdc2-0', usage_metadata={'input_tokens': 13, 'output_tokens': 21, 'total_tokens': 34, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})

In [52]:
ensemble_retriever.invoke('What is Abstractive Question Answering?')

[Document(metadata={'page_label': '6', 'page': 5, 'subject': '', 'ptex.fullbanner': 'This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) kpathsea version 6.3.2', 'author': '', 'keywords': '', 'creator': 'LaTeX with hyperref', 'producer': 'pdfTeX-1.40.21', 'trapped': '/False', 'source': '../Retrieval-Augmented-Generation.pdf', 'title': '', 'moddate': '2021-04-13T00:48:38+00:00', 'total_pages': 19, 'creationdate': '2021-04-13T00:48:38+00:00'}, page_content='even when the correct answer is not in any retrieved document, achieving 11.8% accuracy in such\ncases for NQ, where an extractive model would score 0%.\n4.2 Abstractive Question Answering\nAs shown in Table 2, RAG-Sequence outperforms BART on Open MS-MARCO NLG by 2.6 Bleu\npoints and 2.6 Rouge-L points. RAG approaches state-of-the-art model performance, which is\nimpressive given that (i) those models access gold passages with specific information required to'),
 Document(metadata={'ptex.fullbanner': 'This is pdfTeX, Versio

In [53]:
from langchain import hub

In [54]:
hub.pull("rlm/rag-prompt").pretty_print()

================================ Human Message =================================

You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.
Question: {question} 
Context: {context} 
Answer:


In [55]:
prompt = hub.pull("rlm/rag-prompt")
prompt

ChatPromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, metadata={'lc_hub_owner': 'rlm', 'lc_hub_repo': 'rag-prompt', 'lc_hub_commit_hash': '50442af133e61576e74536c6556cefe1fac147cad032f4377b60c436e6cdcb6e'}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, template="You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.\nQuestion: {question} \nContext: {context} \nAnswer:"), additional_kwargs={})])

In [56]:
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

In [57]:
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

In [58]:
rag_chain = (
    {"context": ensemble_retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

rag_chain

{
  context: EnsembleRetriever(retrievers=[VectorStoreRetriever(tags=['Chroma', 'OpenAIEmbeddings'], vectorstore=<langchain_community.vectorstores.chroma.Chroma object at 0x000001EC58891B20>, search_kwargs={'k': 3}), BM25Retriever(vectorizer=<rank_bm25.BM25Okapi object at 0x000001EC59CBD460>, k=3)], weights=[0.3, 0.7])
           | RunnableLambda(format_docs),
  question: RunnablePassthrough()
}
| ChatPromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, metadata={'lc_hub_owner': 'rlm', 'lc_hub_repo': 'rag-prompt', 'lc_hub_commit_hash': '50442af133e61576e74536c6556cefe1fac147cad032f4377b60c436e6cdcb6e'}, messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, template="You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences

In [59]:
response = rag_chain.invoke("What is Abstractive Question Answering?")
print(response)

Abstractive Question Answering (QA) refers to the ability of models to generate answers in a free-form manner rather than simply extracting them from provided documents. This approach allows for more flexible and nuanced responses, as seen in RAG models that outperform traditional extractive methods. It enables the generation of answers that may not be directly found in the source material.


Abstractive Question Answering (QA) refers to the ability of models to generate answers in a free-form manner rather than simply extracting them from provided documents. This approach allows for more flexible and nuanced responses, as seen in RAG models that outperform traditional extractive methods. It enables the generation of answers that may not be directly found in the source material.

In [61]:
from langchain.chains import RetrievalQA

In [62]:
normal_chain = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=vectorstore_retreiver
)
normal_chain

RetrievalQA(verbose=False, combine_documents_chain=StuffDocumentsChain(verbose=False, llm_chain=LLMChain(verbose=False, prompt=ChatPromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context'], input_types={}, partial_variables={}, template="Use the following pieces of context to answer the user's question. \nIf you don't know the answer, just say that you don't know, don't try to make up an answer.\n----------------\n{context}"), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['question'], input_types={}, partial_variables={}, template='{question}'), additional_kwargs={})]), llm=ChatOpenAI(client=<openai.resources.chat.completions.completions.Completions object at 0x000001EC5DEACFE0>, async_client=<openai.resources.chat.completions.completions.AsyncCompletions object at 0x000001EC5DEBE930>, root_client=<openai.OpenAI object at

In [63]:
hybrid_chain = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=ensemble_retriever
)
hybrid_chain

RetrievalQA(verbose=False, combine_documents_chain=StuffDocumentsChain(verbose=False, llm_chain=LLMChain(verbose=False, prompt=ChatPromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context'], input_types={}, partial_variables={}, template="Use the following pieces of context to answer the user's question. \nIf you don't know the answer, just say that you don't know, don't try to make up an answer.\n----------------\n{context}"), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['question'], input_types={}, partial_variables={}, template='{question}'), additional_kwargs={})]), llm=ChatOpenAI(client=<openai.resources.chat.completions.completions.Completions object at 0x000001EC5DEACFE0>, async_client=<openai.resources.chat.completions.completions.AsyncCompletions object at 0x000001EC5DEBE930>, root_client=<openai.OpenAI object at

In [64]:
response1 = normal_chain.invoke("What is Abstractive Question Answering?")
response1

{'query': 'What is Abstractive Question Answering?',
 'result': 'Abstractive Question Answering refers to a type of question answering that goes beyond simply extracting information from a given text. Instead of pulling out exact phrases or sentences, it generates answers in a free-form manner, often rephrasing or summarizing the information to provide a more coherent and contextually relevant response. This approach allows for more flexibility and creativity in answering questions, as it can synthesize information from multiple sources or present it in a way that is not directly quoted from the text.'}

In [65]:
print(response1['result'])

Abstractive Question Answering refers to a type of question answering that goes beyond simply extracting information from a given text. Instead of pulling out exact phrases or sentences, it generates answers in a free-form manner, often rephrasing or summarizing the information to provide a more coherent and contextually relevant response. This approach allows for more flexibility and creativity in answering questions, as it can synthesize information from multiple sources or present it in a way that is not directly quoted from the text.


Abstractive Question Answering refers to a type of question answering that goes beyond simply extracting information from a given text. Instead of pulling out exact phrases or sentences, it generates answers in a free-form manner, often rephrasing or summarizing the information to provide a more coherent and contextually relevant response. This approach allows for more flexibility and creativity in answering questions, as it can synthesize information from multiple sources or present it in a way that is not directly quoted from the text.

In [66]:
response2 = hybrid_chain.invoke("What is Abstractive Question Answering?")
response2

{'query': 'What is Abstractive Question Answering?',
 'result': 'Abstractive Question Answering is a type of question answering that goes beyond simply extracting answers from a given text. Instead, it involves generating answers in a free-form manner, allowing for more natural and coherent responses that may not directly quote the source material. This approach can provide more comprehensive answers by synthesizing information from multiple sources or rephrasing content to better address the question asked.'}

In [67]:
print(response2['result'])

Abstractive Question Answering is a type of question answering that goes beyond simply extracting answers from a given text. Instead, it involves generating answers in a free-form manner, allowing for more natural and coherent responses that may not directly quote the source material. This approach can provide more comprehensive answers by synthesizing information from multiple sources or rephrasing content to better address the question asked.


Abstractive Question Answering is a type of question answering that goes beyond simply extracting answers from a given text. Instead, it involves generating answers in a free-form manner, allowing for more natural and coherent responses that may not directly quote the source material. This approach can provide more comprehensive answers by synthesizing information from multiple sources or rephrasing content to better address the question asked.