In [2]:
import os
from dotenv import load_dotenv

load_dotenv()

os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
os.environ["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY")

In [3]:
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

In [4]:
documents = [
    "This is a list which containing sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings.",
    "Understanding document structure aids in keyword extraction.",
    "Efficient keyword extraction enhances search accuracy.",
    "Semantic similarity improves document retrieval performance.",
    "Machine learning algorithms can optimize keyword extraction methods."
]

In [9]:
documents

['This is a list which containing sample documents.',
 'Keywords are important for keyword-based search.',
 'Document analysis involves extracting keywords.',
 'Keyword-based search relies on sparse embeddings.',
 'Understanding document structure aids in keyword extraction.',
 'Efficient keyword extraction enhances search accuracy.',
 'Semantic similarity improves document retrieval performance.',
 'Machine learning algorithms can optimize keyword extraction methods.']

In [10]:
len(documents)

8

In [13]:
document_embeddings = embeddings.embed_documents(documents)

In [14]:
len(document_embeddings)

8

In [15]:
len(document_embeddings[0])

1536

In [16]:
for i, embedding in enumerate(document_embeddings):
    print(f"Document {i+1} embedding: {embedding}")

Document 1 embedding: [0.006497232709079981, 0.031100677326321602, 0.051674194633960724, -0.02139594964683056, -0.003349839011207223, -0.060581792145967484, -0.017979683354496956, 0.011792445555329323, 0.02011801302433014, 0.007307014428079128, -0.014980960637331009, -0.018878035247325897, -0.01765071041882038, -0.038970742374658585, 0.019978832453489304, 0.05921528488397598, -0.005782347172498703, 0.02169961854815483, 0.010185535065829754, 0.03740179166197777, 0.045853886753320694, 0.013854858465492725, -0.018549062311649323, 0.010419612750411034, 0.0040805405005812645, -0.022028591483831406, -0.06199890747666359, -0.007730884477496147, 0.017486222088336945, -0.05038360506296158, -0.00028745667077600956, -0.03578222915530205, -0.016549913212656975, 0.019156398251652718, -0.0148544330149889, 0.03487122431397438, 0.02180084027349949, 0.0054723527282476425, -0.029152140021324158, -0.039122577756643295, -0.023496320471167564, 0.011533061973750591, 0.035200197249650955, -0.0001384892675559

In [17]:
documents

['This is a list which containing sample documents.',
 'Keywords are important for keyword-based search.',
 'Document analysis involves extracting keywords.',
 'Keyword-based search relies on sparse embeddings.',
 'Understanding document structure aids in keyword extraction.',
 'Efficient keyword extraction enhances search accuracy.',
 'Semantic similarity improves document retrieval performance.',
 'Machine learning algorithms can optimize keyword extraction methods.']

In [18]:
query = "Natural language processing techniques enhance keyword extraction efficiency."

In [19]:
query_embedding = embeddings.embed_query(query)

In [20]:
print("Query embedding:", query_embedding)

Query embedding: [-0.04618031904101372, 0.042411383241415024, 0.010175049304962158, -0.002978327451273799, -0.0035171338822692633, -0.013494530692696571, -0.012097424827516079, 0.07659175246953964, 0.014360953122377396, 0.028765227645635605, 0.03203597292304039, 0.012249048799276352, -0.05380483716726303, 0.0033113586250692606, 0.037104543298482895, 0.0047951070591807365, -0.009135342203080654, 0.014133517630398273, 0.043927621096372604, -0.007906105369329453, 0.06719106435775757, -0.002465242752805352, 0.0041236295364797115, 0.011740025132894516, 0.01126349251717329, 0.013635324314236641, 0.030346449464559555, 0.05956654995679855, -0.0002061137929558754, -0.015563114546239376, 0.005052326247096062, -0.016353724524378777, 0.02356669306755066, 0.011729194782674313, -0.0001435858430340886, 0.022981857880949974, 0.04397094249725342, -0.006898889318108559, -0.011382625438272953, 0.02761721797287464, 0.04147997871041298, -0.01515156403183937, 0.00995302852243185, 0.04277961328625679, -0.023

In [21]:
len(query_embedding)

1536

In [22]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
similarities = cosine_similarity(np.array([query_embedding]), document_embeddings)

In [24]:
similarities

array([[0.19255612, 0.56717335, 0.5707639 , 0.47683139, 0.61555722,
        0.7376984 , 0.41570045, 0.70959837]])

In [25]:
most_similar_index = np.argmax(similarities)

In [26]:
most_similar_index

np.int64(5)

In [27]:
most_similar_document = documents[most_similar_index]

In [28]:
most_similar_document

'Efficient keyword extraction enhances search accuracy.'

In [29]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [30]:
similarity_score = similarities[0][most_similar_index]

In [31]:
similarity_score

np.float64(0.7376983954347266)

In [32]:
sorted_indices = np.argsort(similarities[0])[::-1]

In [33]:
sorted_indices

array([5, 7, 4, 2, 1, 3, 6, 0])

In [34]:
ranked_documents = [(documents[i], similarities[0][i]) for i in sorted_indices]

In [35]:
ranked_documents

[('Efficient keyword extraction enhances search accuracy.',
  np.float64(0.7376983954347266)),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  np.float64(0.7095983739070749)),
 ('Understanding document structure aids in keyword extraction.',
  np.float64(0.6155572227280144)),
 ('Document analysis involves extracting keywords.',
  np.float64(0.5707638950206806)),
 ('Keywords are important for keyword-based search.',
  np.float64(0.5671733489429878)),
 ('Keyword-based search relies on sparse embeddings.',
  np.float64(0.4768313888347677)),
 ('Semantic similarity improves document retrieval performance.',
  np.float64(0.41570044758649805)),
 ('This is a list which containing sample documents.',
  np.float64(0.1925561201659351))]

In [36]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [38]:
print("Ranked Documents:\n")
for rank, (document, similarity) in enumerate(ranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}\n")

Ranked Documents:

Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7376983954347266

Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7095983739070749

Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.6155572227280144

Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.5707638950206806

Rank 5: Document - 'Keywords are important for keyword-based search.', Similarity Score - 0.5671733489429878

Rank 6: Document - 'Keyword-based search relies on sparse embeddings.', Similarity Score - 0.4768313888347677

Rank 7: Document - 'Semantic similarity improves document retrieval performance.', Similarity Score - 0.41570044758649805

Rank 8: Document - 'This is a list which containing sample documents.', Similarity Score - 0.1925561201659351



In [39]:
print("Top 4 Documents:\n")
for rank, (document, similarity) in enumerate(ranked_documents[:4], start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}\n")

Top 4 Documents:

Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7376983954347266

Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7095983739070749

Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.6155572227280144

Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.5707638950206806



In [40]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [41]:
# !pip install rank_bm25

In [42]:
from rank_bm25 import BM25Okapi

In [43]:
top_4_documents = [doc[0] for doc in ranked_documents[:4]]

In [44]:
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [45]:
tokenized_top_4_documents = [doc.split() for doc in top_4_documents]

In [46]:
tokenized_top_4_documents

[['Efficient', 'keyword', 'extraction', 'enhances', 'search', 'accuracy.'],
 ['Machine',
  'learning',
  'algorithms',
  'can',
  'optimize',
  'keyword',
  'extraction',
  'methods.'],
 ['Understanding',
  'document',
  'structure',
  'aids',
  'in',
  'keyword',
  'extraction.'],
 ['Document', 'analysis', 'involves', 'extracting', 'keywords.']]

In [47]:
tokenized_query = query.split()

In [48]:
tokenized_query

['Natural',
 'language',
 'processing',
 'techniques',
 'enhance',
 'keyword',
 'extraction',
 'efficiency.']

In [49]:
bm25 = BM25Okapi(tokenized_top_4_documents)

In [50]:
bm25

In [51]:
bm25_scores = bm25.get_scores(tokenized_query)

In [52]:
bm25_scores

array([0.1907998 , 0.16686672, 0.17803252, 0.        ])

In [53]:
sorted_indices2 = np.argsort(bm25_scores)[::-1]

In [54]:
sorted_indices2

array([0, 2, 1, 3])

In [55]:
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [56]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [57]:
reranked_documents = [(top_4_documents[i], bm25_scores[i]) for i in sorted_indices2]

In [58]:
reranked_documents

[('Efficient keyword extraction enhances search accuracy.',
  np.float64(0.19079979534096053)),
 ('Understanding document structure aids in keyword extraction.',
  np.float64(0.1780325227902643)),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  np.float64(0.1668667199671815)),
 ('Document analysis involves extracting keywords.', np.float64(0.0))]

In [59]:
print("Rerank of top 4 Documents:\n")
for rank, (document, similarity) in enumerate(reranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}\n")

Rerank of top 4 Documents:

Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.19079979534096053

Rank 2: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.1780325227902643

Rank 3: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.1668667199671815

Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.0



In [60]:
ranked_documents[:4]

[('Efficient keyword extraction enhances search accuracy.',
  np.float64(0.7376983954347266)),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  np.float64(0.7095983739070749)),
 ('Understanding document structure aids in keyword extraction.',
  np.float64(0.6155572227280144)),
 ('Document analysis involves extracting keywords.',
  np.float64(0.5707638950206806))]

## **BM_25**

In [61]:
reranked_documents

[('Efficient keyword extraction enhances search accuracy.',
  np.float64(0.19079979534096053)),
 ('Understanding document structure aids in keyword extraction.',
  np.float64(0.1780325227902643)),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  np.float64(0.1668667199671815)),
 ('Document analysis involves extracting keywords.', np.float64(0.0))]

In [62]:
# !pip install cohere

In [ ]:
from langchain.retrievers.document_compressors import CohereRerank

In [68]:
COHERE_API_KEY = os.getenv("COHERE_API_KEY")

co = CohereRerank(cohere_api_key=COHERE_API_KEY, model="rerank-english-v3.0")

In [66]:
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [67]:
query

'Natural language processing techniques enhance keyword extraction efficiency.'

In [70]:
response = co.rerank(
    model="rerank-english-v3.0",
    query="Natural language processing techniques enhance keyword extraction efficiency.",
    documents=top_4_documents
)

In [74]:
print(response)

[{'index': 0, 'relevance_score': 0.99411184}, {'index': 1, 'relevance_score': 0.9129032}, {'index': 2, 'relevance_score': 0.32885265}]
